### ISSUE TITLE
Error when building Storage objects

### ISSUE THREAD

**Issue by ffdarkpenguin** [HewlettPackard/oneview-redfish-toolkit#152]
When you access /redfish/v1/Systems/30303437-3034-4D32-3230-313133364752/Storage/1 (any uuid) sometimes is replies correctly sometimes it gives you 500 error. Out of 8 tests with same URL just pressing reload around 50% of time if failed other 50% worked fine. The log, as stated in US 151 is useless:
2017-10-30 19:18:55,266 - werkzeug - INFO - 192.168.200.30 - - [30/Oct/2017 19:18:55] "GET /redfish/v1/Systems/30303437-3034-4D32-3230-313133364752/Storage/1 HTTP/1.1" 200 -
2017-10-30 19:18:56,470 - root - ERROR - Unexpected error:

**Comment by ricardoas** [comment]
Rephrasing: due to the lack of guarantees on the order of the list of adapters in a given Server Hardware Type returned by OneView, [this construct](https://github.com/HewlettPackard/oneview-redfish-toolkit/blob/master/oneview_redfish_toolkit/api/storage.py#L74) can fail when attempting to insert an object directly at a non-existent index.

I highly recommend not to rely on index for building collection objects. Just appending the new object should be fine.
