### ISSUE TITLE
Enable HTTPS protocol

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#44]

**Comment by ffdarkpenguin** [comment]
Need to decided what you want:
Options:
1. always run https
2. https is optional

In either cases you need configuration setup minimal im my point of view:
1. HTTPSEnabled: True/False
2. CAFile: path to ca cert
3. ServerCert: path to server cert
4. ServerKey: path to server key

this sould be in redfish.ini

The problem: run.py don´t know about this file and he starts the app server. So there' s no way for him to know without reading the file. Do this there and in the app is bad.

Of course you can hardcode this in run.py and ask the users to edit our code or yet, used environment vars(ARGH INHO).

IMHO:
Add configuration to ini file
Add a min to app.py calling run based on config options
Get rid of run.py
Add other options to ini file: port and ip/interface to bind to

Other improvements IMHO:
rename ini file to conf file. Ini is Windows stuff. Linux uses conf by default.

**Comment by ffdarkpenguin** [comment]
Due to lack of response for the question above the following solution was implemented:
1. added ssl section to redfish.conf with the values:
SSLType: one of: disabled (ssl will be disabled) adhoc (ssl is enabled with self-signed key generated by the server) certs (ssl is enabled and will use certs provided by user in the fields below
SSLCertFile: The user ssl cert file
SSLKeyFile: The user ssl cert key file without password

2. added redfish_port to redfish section of redfish.conf file to indicate which port to use.

3. modified run.py to load config file and run app according to ssl config and use the port indicated

PROBLEM NOT SOLVED: when the user provide an invalid cert file the app generates a ssl an exception that cant be caught by the app launch.

4. updated the documentation regarding the ne fields on the conf file.

**Comment by ricardoas** [comment]
This work assumes the user have `openssl` lib installed as well as `pyOpenSSL` and I see no updates on `requirements.txt` nor in the "Requirements" section on README file. 

We're also not loading the config file using util functions created just for it, not logging and the variable `port` is not being used anywhere...

I'll reopen so that we can figure out what to do, ok?

**Comment by ffdarkpenguin** [comment]
Fixed the fact that was not using the port variable; Added pyOpenSSL to requirements.txt, changed prints to log.error()
